puts "Creating breeds..."

dog = Species.find_by(name: "dog")
Breed.find_or_create_by!(name: "German Shepherd", species: dog)
Breed.find_or_create_by!(name: "Toy Poodle", species: dog)
Breed.find_or_create_by!(name: "Chihuahua", species: dog)
Breed.find_or_create_by!(name: "Miniature Dachshund", species: dog)
Breed.find_or_create_by!(name: "Shiba Inu", species: dog)
Breed.find_or_create_by!(name: "Mixed", species: dog)
Breed.find_or_create_by!(name: "Pomeranian", species: dog)
Breed.find_or_create_by!(name: "Miniature Schnauzer", species: dog)
Breed.find_or_create_by!(name: "French Bulldog", species: dog)
Breed.find_or_create_by!(name: "Yorkshire Terrier", species: dog)
Breed.find_or_create_by!(name: "Maltese", species: dog)
Breed.find_or_create_by!(name: "Labrador Retriever", species: dog)
Breed.find_or_create_by!(name: "Golden Retriever", species: dog)
Breed.find_or_create_by!(name: "King Charles Spaniel", species: dog)
Breed.find_or_create_by!(name: "Corgi", species: dog)
Breed.find_or_create_by!(name: "Shih Tzu", species: dog)
Breed.find_or_create_by!(name: "Pug", species: dog)
Breed.find_or_create_by!(name: "Beagle", species: dog)
Breed.find_or_create_by!(name: "Boston Terrier", species: dog)
Breed.find_or_create_by!(name: "Jack Russell Terrier", species: dog)
Breed.find_or_create_by!(name: "Papillon", species: dog)
puts "------------- DOG BREEDS FINISHED -------------"

cat = Species.find_by(name: "cat")
Breed.find_or_create_by!(name: "British Shorthair", species: cat)
Breed.find_or_create_by!(name: "Persian", species: cat)
Breed.find_or_create_by!(name: "Mixed", species: cat)
Breed.find_or_create_by!(name: "Exotic shorthair", species: cat)
Breed.find_or_create_by!(name: "Domestic shorthair", species: cat)
Breed.find_or_create_by!(name: "Scottish Fold", species: cat)
Breed.find_or_create_by!(name: "Munchkin", species: cat)
Breed.find_or_create_by!(name: "American Shorthair", species: cat)
Breed.find_or_create_by!(name: "Norwegian Forest Cat", species: cat)
Breed.find_or_create_by!(name: "Maine Coon", species: cat)
Breed.find_or_create_by!(name: "British Shorthair", species: cat)
Breed.find_or_create_by!(name: "Ragdoll", species: cat)
Breed.find_or_create_by!(name: "Russian Blue", species: cat)
Breed.find_or_create_by!(name: "Persian", species: cat)
Breed.find_or_create_by!(name: "Bengal", species: cat)
Breed.find_or_create_by!(name: "Siamese", species: cat)
Breed.find_or_create_by!(name: "Sphynx", species: cat)
Breed.find_or_create_by!(name: "Abyssinian", species: cat)
puts "------------- CAT BREEDS FINISHED -------------"

bird = Species.find_by(name: "bird")
Breed.find_or_create_by!(name: "Budgerigar", species: bird)
Breed.find_or_create_by!(name: "Cockatiel", species: bird)
Breed.find_or_create_by!(name: "Lovebird", species: bird)
Breed.find_or_create_by!(name: "Java Sparrow", species: bird)
Breed.find_or_create_by!(name: "Canary", species: bird)
Breed.find_or_create_by!(name: "Zebra Finch", species: bird)
Breed.find_or_create_by!(name: "Quaker Parrot", species: bird)
Breed.find_or_create_by!(name: "Conure", species: bird)
Breed.find_or_create_by!(name: "African Grey Parrot", species: bird)
Breed.find_or_create_by!(name: "Cockatoo", species: bird)
Breed.find_or_create_by!(name: "Macaw", species: bird)
Breed.find_or_create_by!(name: "Dove", species: bird)
Breed.find_or_create_by!(name: "Lorikeet", species: bird)
Breed.find_or_create_by!(name: "Eclectus Parrot", species: bird)
puts "------------- BIRD BREEDS FINISHED -------------"

horse = Species.find_by(name: "horse")
Breed.find_or_create_by!(name: "Thoroughbred", species: horse)
Breed.find_or_create_by!(name: "Arabian", species: horse)
Breed.find_or_create_by!(name: "Quarter Horse", species: horse)
Breed.find_or_create_by!(name: "Warmblood", species: horse)
Breed.find_or_create_by!(name: "Appaloosa", species: horse)
Breed.find_or_create_by!(name: "Paint Horse", species: horse)
Breed.find_or_create_by!(name: "Friesian", species: horse)
Breed.find_or_create_by!(name: "Morgan", species: horse)
Breed.find_or_create_by!(name: "Shetland Pony", species: horse)
Breed.find_or_create_by!(name: "Miniature Horse", species: horse)
Breed.find_or_create_by!(name: "Haflinger", species: horse)
Breed.find_or_create_by!(name: "Standardbred", species: horse)
Breed.find_or_create_by!(name: "Mustang", species: horse)
Breed.find_or_create_by!(name: "Clydesdale", species: horse)
puts "------------- HORSE BREEDS FINISHED -------------"

fish = Species.find_by(name: "fish")
Breed.find_or_create_by!(name: "Goldfish", species: fish)
Breed.find_or_create_by!(name: "Medaka", species: fish)
Breed.find_or_create_by!(name: "Betta", species: fish)
Breed.find_or_create_by!(name: "Guppy", species: fish)
Breed.find_or_create_by!(name: "Neon Tetra", species: fish)
Breed.find_or_create_by!(name: "Koi", species: fish)
Breed.find_or_create_by!(name: "Angelfish", species: fish)
Breed.find_or_create_by!(name: "Molly", species: fish)
Breed.find_or_create_by!(name: "Platy", species: fish)
Breed.find_or_create_by!(name: "Corydoras", species: fish)
Breed.find_or_create_by!(name: "Zebra Danio", species: fish)
Breed.find_or_create_by!(name: "Plecostomus", species: fish)
Breed.find_or_create_by!(name: "Discus", species: fish)
Breed.find_or_create_by!(name: "Gourami", species: fish)
Breed.find_or_create_by!(name: "Oscar", species: fish)
puts "------------- FISH BREEDS FINISHED -------------"


rabbit = Species.find_by(name: "rabbit")
Breed.find_or_create_by!(name: "Holland Lop", species: rabbit)
Breed.find_or_create_by!(name: "Netherland Dwarf", species: rabbit)
Breed.find_or_create_by!(name: "Lionhead", species: rabbit)
Breed.find_or_create_by!(name: "Mini Lop", species: rabbit)
Breed.find_or_create_by!(name: "Rex", species: rabbit)
Breed.find_or_create_by!(name: "Mini Rex", species: rabbit)
Breed.find_or_create_by!(name: "Dutch Rabbit", species: rabbit)
Breed.find_or_create_by!(name: "Flemish Giant", species: rabbit)
Breed.find_or_create_by!(name: "Jersey Wooly", species: rabbit)
Breed.find_or_create_by!(name: "Polish Rabbit", species: rabbit)
Breed.find_or_create_by!(name: "Himalayan", species: rabbit)
Breed.find_or_create_by!(name: "Satin", species: rabbit)
Breed.find_or_create_by!(name: "Californian", species: rabbit)
Breed.find_or_create_by!(name: "Harlequin", species: rabbit)
puts "------------- RABBIT BREEDS FINISHED -------------"
