// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import CarouselController from "controllers/carousel_controller"
application.register("carousel", CarouselController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import ModalController from "controllers/modal_controller"
application.register("modal", ModalController)

import RatingController from "controllers/rating_controller"
application.register("rating", RatingController)

// import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
// eagerLoadControllersFrom("controllers", application)
